export const GET_RESTAURANTS_ORDER_REQUEST = "GET_RESTAURANTS_ORDERS_REQUEST";
export const GET_RESTAURANTS_ORDER_SUCCESS = "GET_RESTAURANTS_ORDERS_SUCCESS";
export const GET_RESTAURANTS_ORDER_FAILURE = "GET_RESTAURANTS_ORDERS_FAILURE";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDERS_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDERS_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDERS_STATUS_FAILURE";
